server:
  port: 8083

spring:
  application:
    name: booking-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/homecare-realm
  datasource:
    url: jdbc:postgresql://localhost:5432/homecare_booking_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    schemas: public
    # Dòng này giúp Flyway tự sửa lỗi checksum mismatch khi khởi động
    repair-at-start: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/